### PR TITLE
[Java] provide platform specific jni and jar for Java bindings

### LINKED ISSUE #2234: [wasmedge-java] Failing to build bindings, please help or provide binaries
### Current State

Currently, bindings for Go and Rust have been published, but the Java bindings have to be built manually. By the way, the building fails locally on my end:

```sh
wasmedge-java $ gradle build
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

> Task :compileJava
Note: .../wasmedge-java/src/main/java/org/wasmedge/ExternRef.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :compileJNI FAILED
-- wasmedge root: 
-- wasmedge include dirs: WasmEdge_INCLUDE_DIRS-NOTFOUND
-- wasmedge lib: 
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find WasmEdge (missing: WasmEdge_INCLUDE_DIRS WasmEdge_LIBRARIES)
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  FindWasmEdge.cmake:63 (find_package_handle_standard_args)
  CMakeLists.txt:10 (find_package)
```

```sh
$HOME/.wasmedge
├── bin
│   ├── show-tflite-tensor
│   ├── wasmedge
│   ├── wasmedge-tensorflow
│   ├── wasmedge-tensorflow-lite
│   └── wasmedgec
├── env
├── include
│   └── wasmedge
│       ├── enum.inc
│       ├── enum_configure.h
│       ├── enum_errcode.h
│       ├── enum_types.h
│       ├── int128.h
│       ├── version.h
│       ├── wasmedge-image.h
│       ├── wasmedge-tensorflow.h
│       ├── wasmedge-tensorflowlite.h
│       └── wasmedge.h
├── lib
│   ├── libtensorflow.so -> /home/direnc/.wasmedge/lib/libtensorflow.so.2.6.0
│   ├── libtensorflow.so.2 -> /home/direnc/.wasmedge/lib/libtensorflow.so.2.6.0
│   ├── libtensorflow.so.2.6 -> /home/direnc/.wasmedge/lib/libtensorflow.so.2.6.0
│   ├── libtensorflow.so.2.6.0
│   ├── libtensorflow_framework.so -> /home/direnc/.wasmedge/lib/libtensorflow_framework.so.2.6.0
│   ├── libtensorflow_framework.so.2 -> /home/direnc/.wasmedge/lib/libtensorflow_framework.so.2.6.0
│   ├── libtensorflow_framework.so.2.6 -> /home/direnc/.wasmedge/lib/libtensorflow_framework.so.2.6.0
│   ├── libtensorflow_framework.so.2.6.0
│   ├── libtensorflowlite_c.so
│   ├── libwasmedge-image_c.so
│   ├── libwasmedge-tensorflow_c.so
│   ├── libwasmedge-tensorflowlite_c.so
│   ├── libwasmedge.so -> libwasmedge.so.0
│   ├── libwasmedge.so.0 -> libwasmedge.so.0.0.1
│   └── libwasmedge.so.0.0.1
└── plugin
    └── libwasmedgePluginWasmEdgeProcess.so
```

### Expected

Could you kindly provide the binaries for Java so that users are able to integrate it directly?

## Environment
x86_64
Ubuntu 20.04

The following information is optional. Please provide them only if you have built from source.
- C++ Compiler version: gcc 9.4.0
- CMake version: 3.16.3
- CMake flags: (e.g. `-DCMAKE_BUILD_TYPE=Release -DWASMEDGE_BUILD_AOT_RUNTIME=ON`) see wasmedge-java
- wasmedge: 0.11.2

I have installed wasmedge with `install.sh` without setting any env vars.

### PR DESCRIPTION
**Pull request by proohit**
This PR attempts to archive wasmedge-java bindings into platform specific jars.

closes #2234

### CODE REVIEW

**Comment by juntao** [comment]
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Comment by proohit** [comment]
I've tested this only with a version that works for the current bindings. That'd be `wasmedge 0.11.2`

**Comment by proohit** [comment]
Tested working on Ubuntu 22.04 only.

Currently OSX AARCH64 doesn't work as it throws

```java
Exception in thread "main" java.lang.UnsatisfiedLinkError: Can't load library: /var/folders/c3/8kzrk3wj73sb7gpqc95p3m880000gq/T/nativeutils164953247979250/libwasmedge_jni.dylib
```
But that seems like a OSX specific thing.

**Comment by proohit** [comment]
Artifacts are being uploaded like that: https://github.com/WasmEdge/WasmEdge/actions/runs/6654565675?pr=2980

**Comment by dannypsnl** [comment]
You need to provide signed commits to pass DCO check.

**Comment by proohit** [comment]
> You need to provide signed commits to pass DCO check.

done.

File: bindings/java/wasmedge-java/src/main/java/org/wasmedge/WasmEdge.java [hunk 1]
```diff
@@ -107,14 +111,14 @@ private static String libraryPath() throws IOException {
...
-          default:
-              throw new RuntimeException("Invalid log level " + logLevel);
+            case ERROR:
+                setErrorLevel();
+                return;
+            case DEBUG:
+                setDebugLevel();
+                return;
+            default:
+                throw new RuntimeException("Invalid log level " + logLevel);
```
Comment (dannypsnl) [inline bindings/java/wasmedge-java/src/main/java/org/wasmedge/WasmEdge.java:121]: I don'y see any reason to do indention modification.

File: bindings/java/wasmedge-java/src/main/java/org/wasmedge/WasmEdge.java [hunk 2]
```diff
@@ -15,7 +15,11 @@ public class WasmEdge {
     private static final String NATIVE_LIBRARY_NAME = "wasmedge_jni";
 
     public static synchronized void init() {
-        System.loadLibrary(NATIVE_LIBRARY_NAME);
+        try {
+            NativeUtils.loadLibraryFromJar("/" + System.mapLibraryName(NATIVE_LIBRARY_NAME));
+        } catch (IOException e) {
+            throw new RuntimeException(e);
+        }
```
Comment (dannypsnl) [inline bindings/java/wasmedge-java/src/main/java/org/wasmedge/WasmEdge.java:22]: If the code is only rewrap the exception, why not let `loadLibraryFromJar` throws correct type?

Comment (dannypsnl) [reply bindings/java/wasmedge-java/src/main/java/org/wasmedge/WasmEdge.java:22]: Also, it's danger to use `"/" + System...`. Do we have any reason to avoid `loadLibraryFromJar` handle these?

**Review by dannypsnl — CHANGES_REQUESTED** [review]

**Comment by dannypsnl** [comment]
I think the big part has no problem, only some minor suggestions, but please update to the latest `master` branch to ensure this is fitting the ABI.

**Comment by proohit** [comment]
> I think the big part has no problem, only some minor suggestions, but please update to the latest `master` branch to ensure this is fitting the ABI.

Thanks for the review. I think updating to match the current wasmedge version is subject for another pr and shouldn't be part of this. There are several minor versions between with many breaking changes in the line.

**Comment by dannypsnl** [comment]
No, I mean if you didn't rebase on the `master` branch and let CI runs on it, the result of the PR might not work in `master`.

File: bindings/java/wasmedge-java/src/main/java/org/wasmedge/WasmEdge.java (hunk 2 above)
Comment (proohit) [reply bindings/java/wasmedge-java/src/main/java/org/wasmedge/WasmEdge.java]: Changed `loadLibraryFromJar` to throw relevant `RuntimeException`s. The reasoning is that I didn't want to introduce breaking changes to the signature of `WasmEdge#init`.

Also, it's not `"/"` meant in the OS `"/"` way. In this case, it looks for the dynamic lib at root of the jar archive (`"/"`) and copies it to `/tmp/wasmedge_jni_tmp/` in the actual filesystem.

**Comment by proohit** [comment]
> No, I mean if you didn't rebase on the `master` branch and let CI runs on it, the result of the PR might not even compiled after merged. Therefore, I believe rebasing is required.

rebased to current master.

**Review by dannypsnl — APPROVED** [review]
