### PR TITLE
[Code Quality] Fix null dereference issues in elem.cpp

### LINKED ISSUE #526: [Code Quality] Issue in lib/executor/instantiate/elem.cpp
```
/home/runner/work/WasmEdge/WasmEdge/lib/executor/instantiate/elem.cpp:48: error: Null Dereference
  pointer `TabInst` last assigned on line 46 could be null and is dereferenced at line 48, column 14.
  46.         auto *TabInst = getTabInstByIdx(StoreMgr, ElemSeg.getIdx());
  47.         /// Check elements fits.
  48.         if (!TabInst->checkAccessBound(
                   ^
  49.                 Offset, static_cast<uint32_t>(InitVals.size()))) {
  50.           spdlog::error(ErrCode::ElemSegDoesNotFit);
```

### LINKED ISSUE #530: [Code Quality] Issue in lib/executor/instantiate/elem.cpp
```
/home/runner/work/WasmEdge/WasmEdge/lib/executor/instantiate/elem.cpp:106: error: Null Dereference
  pointer `ElemInst` last assigned on line 79 could be null and is dereferenced at line 106, column 7.
  104.                AST::ElementSegment::ElemMode::Declarative) {
  105.       /// Drop the element instance.
  106.       ElemInst->clear();
             ^
  107.     }
  108.     Idx++;
```

### LINKED ISSUE #531: [Code Quality] Issue in lib/executor/instantiate/elem.cpp
```
/home/runner/work/WasmEdge/WasmEdge/lib/executor/instantiate/elem.cpp:83: error: Null Dereference
  pointer `ElemInst` last assigned on line 79 could be null and is dereferenced at line 83, column 28.
  81.       /// Table index is checked in validation phase.
  82.       auto *TabInst = getTabInstByIdx(StoreMgr, ElemSeg.getIdx());
  83.       const uint32_t Off = ElemInst->getOffset();
                                 ^
  84. 
  85.       /// Replace table[Off : Off + n] with elem[0 : n].
```

### PR DESCRIPTION
**Pull request by avinal**
## What is changed?
- Add assertion for nullptr before dereferencing
- File: https://github.com/WasmEdge/WasmEdge/blob/master/lib/executor/instantiate/elem.cpp

## Fixes
- Fixes #526 
- Fixes #530 
- Fixes #531

Signed-off-by: Avinal Kumar <avinal.xlvii@gmail.com>

### CODE REVIEW

File: lib/executor/instantiate/elem.cpp [hunk 1]
```diff
@@ -100,8 +102,8 @@ Expect<void> Executor::initTable(Runtime::StoreManager &StoreMgr,
       ///   i32.const n
       ///   table.init idx
       ///   elem.drop idx
-    } else if (ElemSeg.getMode() ==
-               AST::ElementSegment::ElemMode::Declarative) {
+    } else if (ElemInst && ElemSeg.getMode() ==
```
Comment (hydai) [inline lib/executor/instantiate/elem.cpp:105]: I think the `ElemInst` is checked at line 81. So we don't need an extra check here.

**Review by hydai — CHANGES_REQUESTED** [review]

File: lib/executor/instantiate/elem.cpp (hunk 1 above)
Comment (avinal) [reply lib/executor/instantiate/elem.cpp:105]: I can remove it but the code analyzer will throw a warning here maybe.

Comment (hydai) [reply lib/executor/instantiate/elem.cpp:105]: Please remove it. It is pretty sure that this is checked at line 81.

Comment (avinal) [reply lib/executor/instantiate/elem.cpp:105]: Sure

**Review by hydai — APPROVED** [review]

**Review by q82419 — APPROVED** [review]
