### PR TITLE
fix(cli): handle invalid numeric arguments gracefully

### LINKED ISSUE #4588: bug: CLI crashes on invalid numeric arguments due to unhandled std::sto* exceptions
### Summary

When executing a WASM function via the WasmEdge CLI, passing invalid numeric arguments (e.g. non-numeric strings or out-of-range values) causes the runtime to crash with an unhandled exception instead of showing a user-friendly error.

### Current State

The CLI directly uses `std::stol`, `std::stoll`, `std::stof`, and `std::stod` for argument parsing in `runtimeTool.cpp` without exception handling.
If a user passes invalid input (like `"abc"` for an integer), the process terminates with `SIGABRT` due to an uncaught exception.

### **Expected State**

The CLI should catch conversion errors and return a clear, user-friendly error message, such as:

```
Error: Invalid argument 'abc' for parameter 1: expected i32
```

The process should exit gracefully instead of crashing.

### Reproduction steps

1. Install WasmEdge (tested with released version):

   ```bash
   wasmedge --version
   ```
2. Create a simple WASM module with an integer parameter (e.g. `add(i32, i32)`).
3. Execute with an invalid argument:

   ```bash
   wasmedge --reactor add.wasm add abc 5
   ```
4. Observe the crash with an unhandled exception.

### Screenshots

Not applicable (CLI output shown in logs below).

### Any logs you want to share for showing the specific issue

```
libc++abi: terminating due to uncaught exception of type std::invalid_argument: stol: no conversion
zsh: abort      wasmedge --reactor add.wasm add abc 5
Exit code: 134 (SIGABRT)
```

### Components

CLI

### WasmEdge Version or Commit you used

0.14.1

### Operating system information

macOS

### Hardware Architecture

arm64

### Compiler flags and options

_No response_

### PR DESCRIPTION
**Pull request by Meetjain1**
This PR fixes a crash in the CLI when invalid numeric arguments are passed.

When non-numeric or out-of-range values (for example `"abc"` or very large integers) are provided, the CLI previously threw uncaught exceptions and aborted. This change adds exception handling around numeric argument parsing so the CLI fails gracefully with a clear error message and a proper exit code.

Closes #4588

CI checks - https://github.com/Meetjain1/WasmEdge/pull/2

image

### CODE REVIEW

File: lib/driver/runtimeTool.cpp [hunk 1]
```diff
@@ -35,45 +35,67 @@ ToolOnModule(WasmEdge::VM::VM &VM, const std::string &FuncName,
...
-    case TypeCode::F64: {
-      const double Value = std::stod(Opt.Args.value()[I + 1]);
-      FuncArgs.emplace_back(Value);
-      FuncArgTypes.emplace_back(TCode);
-      break;
-    }
-    // TODO: FuncRef and ExternRef
-    default:
-      break;
+    try {
```
Comment (PhantomInTheWire) [inline lib/driver/runtimeTool.cpp]: how about using a template here to avoid duplication?
```cpp
template <typename T, typename Func>
bool parseNumericArg(const std::string &Value, size_t ParamIndex, T &Out,
                     Func Converter) {
  try {
    Out = Converter(Value);
    return true;
  } catch (const std::invalid_argument &) {
    spdlog::error(
        "Invalid argument '{}' for parameter {}: expected numeric value"sv,
        Value, ParamIndex + 1);
    return false;
  } catch (const std::out_of_range &) {
    spdlog::error("Argument '{}' for parameter {}: value out of range"sv, Value,
                  ParamIndex + 1);
    return false;
  }
}
```
something like this

Comment (Meetjain1) [reply lib/driver/runtimeTool.cpp]: Sure will add

**Comment by Meetjain1** [comment]
@hydai PTAL on this PR.

File: lib/driver/runtimeTool.cpp [hunk 2]
```diff
@@ -23,6 +23,25 @@ using namespace std::literals;
...
+// Helper template to parse numeric arguments and catch conversion exceptions
+template <typename T, typename Converter>
+inline bool parseNumericArg(const std::string &Value, size_t ParamIndex, T &Out,
+                            Converter Conv) {
+  try {
+    Out = Conv(Value);
+    return true;
+  } catch (const std::invalid_argument &) {
+    spdlog::error(
+        "Invalid argument '{}' for parameter {}: expected numeric value"sv,
```
Comment (hydai) [inline lib/driver/runtimeTool.cpp]: Since you already know the type, you should display the typename instead of "numeric value."

File: lib/driver/runtimeTool.cpp [hunk 3]
```diff
@@ -23,6 +23,25 @@ using namespace std::literals;
...
+        Value, ParamIndex);
+    return false;
+  } catch (const std::out_of_range &) {
+    spdlog::error("Argument '{}' for parameter {}: value out of range"sv, Value,
```
Comment (hydai) [inline lib/driver/runtimeTool.cpp]: Ditto, we should provide enough information to let users know the expected typename, so it's clearly out of range.

File: lib/driver/runtimeTool.cpp [hunk 4]
```diff
@@ -23,6 +23,25 @@ using namespace std::literals;
 namespace WasmEdge {
 namespace Driver {
 
+// Helper template to parse numeric arguments and catch conversion exceptions
+template <typename T, typename Converter>
+inline bool parseNumericArg(const std::string &Value, size_t ParamIndex, T &Out,
```
Comment (hydai) [inline lib/driver/runtimeTool.cpp]: I don't think we need `inline` keyword here. Templates are implicitly inline.

File: lib/driver/runtimeTool.cpp [hunk 5]
```diff
@@ -23,6 +23,25 @@ using namespace std::literals;
...
+    spdlog::error(
+        "Invalid argument '{}' for parameter {}: expected numeric value"sv,
+        Value, ParamIndex);
+    return false;
+  } catch (const std::out_of_range &) {
+    spdlog::error("Argument '{}' for parameter {}: value out of range"sv, Value,
+                  ParamIndex);
+    return false;
+  }
+}
```
Comment (hydai) [inline lib/driver/runtimeTool.cpp:45]:
```suggestion
template <typename Converter, typename ValVec, typename TypeVec, typename TC>
bool parseNumericArg(const std::string &Value, size_t ParamIndex,
                     Converter Conv, ValVec &FuncArgs, TypeVec &FuncArgTypes,
                     TC TCode) {
  try {
    auto Out = Conv(Value);
    FuncArgs.emplace_back(Out);
    FuncArgTypes.emplace_back(TCode);
    return true;
  } catch (const std::invalid_argument &) {
    spdlog::error(
        "Invalid argument '{}' for parameter {}: expected numeric value"sv,
        Value, ParamIndex + 1);
    return false;
  } catch (const std::out_of_range &) {
    spdlog::error("Argument '{}' for parameter {}: value out of range"sv,
                  Value, ParamIndex + 1);
    return false;
  }
}
```

File: lib/driver/runtimeTool.cpp [hunk 6]
```diff
@@ -35,29 +54,47 @@ ToolOnModule(WasmEdge::VM::VM &VM, const std::string &FuncName,
        I < FuncType.getParamTypes().size() && I + 1 < Opt.Args.value().size();
        ++I) {
     const auto TCode = FuncType.getParamTypes()[I].getCode();
+    const std::string &ArgValue = Opt.Args.value()[I + 1];
```
Comment (hydai) [inline lib/driver/runtimeTool.cpp]:
```suggestion
    const auto &ArgValue = Opt.Args.value()[I + 1];
```

File: lib/driver/runtimeTool.cpp [hunk 7]
```diff
@@ -35,29 +54,47 @@ ToolOnModule(WasmEdge::VM::VM &VM, const std::string &FuncName,
...
+      int32_t Value = 0;
+      if (!parseNumericArg(ArgValue, I, Value, [](const std::string &S) {
+            return static_cast<int32_t>(std::stol(S));
+          })) {
+        return EXIT_FAILURE;
+      }
       FuncArgs.emplace_back(Value);
       FuncArgTypes.emplace_back(TCode);
       break;
     }
```
Comment (hydai) [inline lib/driver/runtimeTool.cpp:72]:
```cpp
    case TypeCode::I32: {
      if (!parseNumericArg(
              ArgValue, I,
              [](const std::string &S) {
                return static_cast<int32_t>(std::stol(S));
              },
              FuncArgs, FuncArgTypes, TCode)) {
        return EXIT_FAILURE;
      }
    }
```

File: lib/driver/runtimeTool.cpp (hunk 2 above)
Comment (Meetjain1) [reply lib/driver/runtimeTool.cpp]: Done.

File: lib/driver/runtimeTool.cpp (hunk 3 above)
Comment (Meetjain1) [reply lib/driver/runtimeTool.cpp]: Done.

File: lib/driver/runtimeTool.cpp (hunk 4 above)
Comment (Meetjain1) [reply lib/driver/runtimeTool.cpp]: Removed.

File: lib/driver/runtimeTool.cpp (hunk 5 above)
Comment (Meetjain1) [reply lib/driver/runtimeTool.cpp:45]: Fixed.

File: lib/driver/runtimeTool.cpp (hunk 6 above)
Comment (Meetjain1) [reply lib/driver/runtimeTool.cpp]: Fixed.

File: lib/driver/runtimeTool.cpp (hunk 7 above)
Comment (Meetjain1) [reply lib/driver/runtimeTool.cpp:72]: fixed.

**Comment by Meetjain1** [comment]
@hydai Addressed all comments with latest CI checks https://github.com/Meetjain1/WasmEdge/pull/2.

**Comment by Meetjain1** [comment]
@hydai anything else needed in this PR?

**Comment by q82419** [comment]
@Meetjain1 

Please rebase to the latest master branch and resolve the conflicts, and then we would merge this PR. Thanks!

**Comment by Meetjain1** [comment]
> @Meetjain1
> 
> Please rebase to the latest master branch and resolve the conflicts, and then we would merge this PR. Thanks!

@q82419 done.

**Review by hydai — APPROVED** [review]
