### PR TITLE
fix(po): reject numeric option values with trailing garbage

### LINKED ISSUE #4787: bug: CLI accepts numeric options with trailing garbage and silently drops parse errors
### Summary

WasmEdge's Program Options (PO) numeric parser silently accepts values with trailing non-numeric characters. Flags such as `--time-limit=100abc` or `--gas-limit 42xyz` are quietly accepted as `100` and `42` instead of being rejected as invalid input. In addition, when a value fails to parse, the error path from `consume_argument` is discarded in two branches of the `ArgumentParser` state machine, so the user never sees any error at all.

### Current State

The helpers `stringToInteger` and `stringToFloating` in `include/po/parser.h` only reject input when no characters at all could be converted (`EndPtr == CStr`). They do not check that the entire string was consumed, so `strtol("123abc", ...)` returns `123` with `"abc"` left unparsed and the parser reports success.

In addition, both returned error messages are hard-coded to the empty string, so if an error ever did reach the CLI, the user would only see a blank line.

Finally, `lib/po/argument_parser.cpp` drops the result of `consume_argument` in two places:

1. In `SubCommandDescriptor::parse`, when consuming a non-escaped value that follows a short/long option (e.g. `--time-limit 100abc`).
2. In `consume_long_option_with_argument`, when consuming the right-hand side of `--option=value` (e.g. `--time-limit=100abc`).

This means that even if the parser did produce a useful error, the top-level parser would still return success and the invalid value would silently reach the runtime. There is also a minor cosmetic bug in the "doesn't need arguments" message where a space is missing between the option name and the rest of the sentence, producing output like `option foodoesn't need arguments.`.

### Expected State

For every registered numeric CLI option (e.g. `--time-limit`, `--gas-limit`, `--memory-page-limit`, and any numeric plugin option), WasmEdge should reject inputs that contain non-numeric trailing content and surface a clear, actionable error message:

```
$ wasmedge --time-limit=100abc module.wasm
invalid integer value: 100abc
```

Parser errors for option values must be propagated to the caller, both for `--option value` and `--option=value` forms, so that the CLI exits with a non-zero status and the user can see the problem.

### Reproduction steps

1. Build WasmEdge from source on the current `master` branch.
2. Run `wasmedge --time-limit=100abc module.wasm`.
3. Observe that the CLI silently accepts `100` as the time limit and runs the module.
4. Run `wasmedge --time-limit 100abc module.wasm` (space-separated form).
5. Observe the same silent acceptance, because the error is dropped by the argument parser.

### Components

CLI

### WasmEdge Version or Commit you used

master @ f3ee7865 (0.17.0-alpha.2-1-gf3ee7865)

### Operating system information

macOS 15.5 (Darwin 24.6.0), also reproducible on Linux.

### Hardware Architecture

arm64 (reproduces on any architecture, numeric parsing is not platform-specific)

### PR DESCRIPTION
**Pull request by officialasishkumar**
## Description

Fixes #4787.

WasmEdge's Program Options (PO) numeric parser silently accepted values with trailing non-numeric characters. `--time-limit=100abc` was accepted as `100`, `--gas-limit 42xyz` as `42`, and so on. On top of that, the `ArgumentParser` state machine discarded the error return from `consume_argument` in two branches, so even when a sub-parser did report a failure the CLI kept going and reported success.

This PR tightens the PO parser so invalid inputs are rejected with a clear message, and wires the discarded error paths back into the caller.

### Root cause

`stringToInteger` / `stringToFloating` in `include/po/parser.h` only treated a conversion as failed when **no** characters were consumed (`EndPtr == CStr`). `strtol("123abc", ...)` returns `123` with `EndPtr` pointing at `"abc"`, which the old check accepted as a valid conversion. Both error paths also returned an empty error message, so even if the error had reached the user they would only have seen a blank line.

Separately, `lib/po/argument_parser.cpp`:

1. In `SubCommandDescriptor::parse`, the non-escaped `--option value` branch called `consume_argument(*CurrentDesc, Arg);` and dropped the result on the floor.
2. In `consume_long_option_with_argument`, the `--option=value` branch did the same for the right-hand side.

So even a fixed parser wouldn't surface any error to the user from those two code paths.

### Changes

- `include/po/parser.h`: require the converter to consume the entire input (`*EndPtr == '\0'`) and include the offending value in the returned error message (`invalid integer value: <value>`, `integer value out of range: <value>`, and equivalents for floats).
- `lib/po/argument_parser.cpp`: propagate `consume_argument` errors in both branches listed above. Also fix a missing space in the existing "doesn't need arguments" error message so it reads `option --foo doesn't need arguments.` instead of `option --foodoesn't need arguments.`.
- `test/po/po.cpp`: extend the parametrized PO test suite with new failure cases covering trailing garbage on both `--option=value` and `--option value` forms, fractional input passed to an integer option (`--b=1.5`), trailing garbage on a `List<int>` positional via `-c 42xyz`, overflow (`--b=99999999999999999999`), and an empty value (`--b=`).

### Before / after (end-to-end)

```
# before
$ wasmedge --time-limit=100abc module.wasm
# ... module runs with TimeLim = 100 ...

# after
$ wasmedge --time-limit=100abc module.wasm
invalid integer value: 100abc
```

## Checklist

Before submitting this PR, please ensure the following:

- [x] **DCO Signed-off**: All commits are signed-off (`git commit -s`). CI workflows will only be approved if DCO check is passed.
- [x] **Commit Messages**: Run `commitlint` on your commit messages to ensure they meet the [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) standards.
- [x] **Local Tests Passed**: Provide a screenshot or logs below to prove that you have passed the test suites locally.

### `poTests` (42 tests, includes 7 new cases)

```
[----------] 27 tests from InstantiationName/GeneralOptions
...
[ RUN      ] InstantiationName/GeneralOptions.Test/test___b_1abc
invalid integer value: 1abc
[       OK ] InstantiationName/GeneralOptions.Test/test___b_1abc (0 ms)
[ RUN      ] InstantiationName/GeneralOptions.Test/test___b_option_1abc
invalid integer value: 1abc
[       OK ] InstantiationName/GeneralOptions.Test/test___b_option_1abc (0 ms)
[ RUN      ] InstantiationName/GeneralOptions.Test/test__b_1abc
invalid integer value: 1abc
[       OK ] InstantiationName/GeneralOptions.Test/test__b_1abc (0 ms)
[ RUN      ] InstantiationName/GeneralOptions.Test/test___b_1_5
invalid integer value: 1.5
[       OK ] InstantiationName/GeneralOptions.Test/test___b_1_5 (0 ms)
[ RUN      ] InstantiationName/GeneralOptions.Test/test__c_42xyz
invalid integer value: 42xyz
[       OK ] InstantiationName/GeneralOptions.Test/test__c_42xyz (0 ms)
[ RUN      ] InstantiationName/GeneralOptions.Test/test___b_99999999999999999999
integer value out of range: 99999999999999999999
[       OK ] InstantiationName/GeneralOptions.Test/test___b_99999999999999999999 (0 ms)
[ RUN      ] InstantiationName/GeneralOptions.Test/test___b_
invalid integer value: 
[       OK ] InstantiationName/GeneralOptions.Test/test___b_ (0 ms)
...
[==========] 42 tests from 4 test suites ran. (0 ms total)
[  PASSED  ] 42 tests.
```

### Full local `ctest` (fast unit tests)

```
Test project /tmp/wasmedge-work/WasmEdge/build
      Start  1: wasmedgeCommonTests
 1/17 Test  #1: wasmedgeCommonTests ................   Passed    0.01 sec
 2/17 Test  #2: wasmedgeLoaderFileMgrTests .........   Passed    0.01 sec
 3/17 Test  #3: wasmedgeLoaderASTTests .............   Passed    0.34 sec
 4/17 Test  #4: wasmedgeLoaderSerializerTests ......   Passed    0.32 sec
 5/17 Test  #5: wasmedgeExecutorCoreTests ..........   Passed    3.31 sec
 6/17 Test  #6: wasmedgeExecutorRegressionTests ....   Passed    0.35 sec
 7/17 Test  #7: wasmedgeValidatorRegressionTests ...   Passed    0.33 sec
 8/17 Test  #8: wasmedgeComponentRegressionTests ...   Passed    0.30 sec
 9/17 Test  #9: wasmedgeThreadTests ................   Passed    0.70 sec
10/17 Test #10: wasiSocketTests ....................   Passed    0.35 sec
11/17 Test #11: wasiTests ..........................   Passed    2.23 sec
12/17 Test #12: wasmedgeHostMockTests ..............   Passed    0.30 sec
13/17 Test #13: expectedTests ......................   Passed    0.01 sec
14/17 Test #14: spanTests ..........................   Passed    0.01 sec
15/17 Test #15: poTests ............................   Passed    0.01 sec
16/17 Test #16: wasmedgeMemInstanceTests ...........   Passed    0.33 sec
17/17 Test #17: wasmedgeErrinfoTests ...............   Passed    0.01 sec

100% tests passed, 0 tests failed out of 17
```

### End-to-end CLI reproduction

```
$ ./build/tools/wasmedge/wasmedge --time-limit=100abc /tmp/empty.wasm
invalid integer value: 100abc

$ ./build/tools/wasmedge/wasmedge --time-limit 100abc /tmp/empty.wasm
invalid integer value: 100abc

$ ./build/tools/wasmedge/wasmedge --gas-limit 42xyz /tmp/empty.wasm
invalid integer value: 42xyz

$ ./build/tools/wasmedge/wasmedge --memory-page-limit=10abc /tmp/empty.wasm
invalid integer value: 10abc

$ ./build/tools/wasmedge/wasmedge --time-limit=99999999999999999999 /tmp/empty.wasm
integer value out of range: 99999999999999999999

$ ./build/tools/wasmedge/wasmedge --time-limit=100 /tmp/empty.wasm
[...normal loading error for empty wasm file - flag accepted...]
```

Lint checks: `clang-format`, `lineguard` (via `cargo install lineguard@0.1.7`) and `codespell 2.4.1` all pass on the touched files.

### CODE REVIEW

File: include/po/parser.h [hunk 1]
```diff
@@ -33,9 +33,10 @@ stringToInteger(ConvResultT (&Conv)(const char *, char **, int),
   auto SavedErrNo = std::exchange(errno, 0);
   const auto Result = Conv(CStr, &EndPtr, 10);
   std::swap(SavedErrNo, errno);
-  if (EndPtr == CStr) {
+  if (EndPtr == CStr || *EndPtr != '\0') {
```
Comment (ibmibmibm) [inline include/po/parser.h]: The latter condition is sufficient for the failure case.
`if (*EndPtr!= '\0') {`

**Review by ibmibmibm — CHANGES_REQUESTED** [review]

File: include/po/parser.h [hunk 2]
```diff
@@ -33,9 +33,10 @@ stringToInteger(ConvResultT (&Conv)(const char *, char **, int),
...
     return cxx20::unexpected<Error>(std::in_place, ErrCode::InvalidArgument,
-                                    ""s);
+                                    "invalid integer value: "s +
```
Comment (ibmibmibm) [inline include/po/parser.h]: Use `fmt::format` to generate error messages

**Review by ibmibmibm — CHANGES_REQUESTED** [review]

File: include/po/parser.h (hunk 1 above)
Comment (officialasishkumar) [reply include/po/parser.h]: I kept the trailing-garbage check and added an explicit empty-value guard, so `--b=` still fails as invalid input.

File: include/po/parser.h (hunk 2 above)
Comment (officialasishkumar) [reply include/po/parser.h]: Switched the numeric parser errors in `include/po/parser.h` to `fmt::format`.

File: lib/po/argument_parser.cpp [hunk 3]
```diff
@@ -277,9 +279,12 @@ ArgumentParser::SubCommandDescriptor::consume_long_option_with_argument(
     } else if (ArgumentDescriptor *CurrentDesc = *Res; !CurrentDesc) {
       return cxx20::unexpected<Error>(std::in_place, ErrCode::InvalidArgument,
                                       "option "s + std::string(Option) +
```
Comment (ibmibmibm) [inline lib/po/argument_parser.cpp]: change to `fmt::format` too

**Review by ibmibmibm — CHANGES_REQUESTED** [review]

File: lib/po/argument_parser.cpp (hunk 3 above)
Comment (officialasishkumar) [reply lib/po/argument_parser.cpp]: Updated this error construction to use `fmt::format` as requested.

**Review by ibmibmibm — APPROVED** [review]

**Review by q82419 — CHANGES_REQUESTED** [review]
Please fix the lint issue.

**Comment by officialasishkumar** [comment]
Fixed the lint failure in d6f0f41e

**Review by q82419 — APPROVED** [review]
