### PR TITLE
fix(tools): handle exported function not found case in reactor mode

### LINKED ISSUE #4637: bug: Null pointer dereference in std::vector::size() at runtimeTool.cpp
### Summary

Run the following command:

```bash
wasmedge run --reactor test1.wasm _initialize
```

Observed output:
```
AddressSanitizer:DEADLYSIGNAL
=================================================================
[1m[31m==2708373==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000008 (pc 0x7dc0b6a0fffc bp 0x7ffe1d14a560 sp 0x7ffe1d1496d0 T0)
[1m[0m==2708373==The signal is caused by a READ memory access.
==2708373==Hint: address points to the zero page.
    #0 0x7dc0b6a0fffc in std::vector<WasmEdge::ValType, std::allocator<WasmEdge::ValType> >::size() const /usr/include/c++/11/bits/stl_vector.h:919
    #1 0x7dc0b6a0fffc in ToolOnModule /work/harnesses/sources/WasmEdge/lib/driver/runtimeTool.cpp:35
    #2 0x7dc0b6a228c3 in WasmEdge::Driver::Tool(WasmEdge::Driver::DriverToolOptions&) /work/harnesses/sources/WasmEdge/lib/driver/runtimeTool.cpp:511
    #3 0x7dc0b69e53fa in WasmEdge::Driver::UniTool(int, char const**, WasmEdge::Driver::ToolType) /work/harnesses/sources/WasmEdge/lib/driver/uniTool.cpp:69
    #4 0x7dc0b69454f8 in WasmEdge_Driver_UniTool /work/harnesses/sources/WasmEdge/lib/api/wasmedge.cpp:3384
    #5 0x5ba556caa195 in main /work/harnesses/sources/WasmEdge/tools/wasmedge/wasmedge.cpp:18
    #6 0x7dc0b62acd8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #7 0x7dc0b62ace3f in __libc_start_main_impl ../csu/libc-start.c:392
    #8 0x5ba556caa0c4 in _start (/work/harnesses/compiled-binaries/wasmedge+0x10c4)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /usr/include/c++/11/bits/stl_vector.h:919 in std::vector<WasmEdge::ValType, std::allocator<WasmEdge::ValType> >::size() const
==2708373==ABORTING

```

### Current State

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7da521c00640 (LWP 2708518)]
[Thread 0x7da521c00640 (LWP 2708518) exited]

Thread 1 "wasmedge" received signal SIGSEGV, Segmentation fault.
0x00007da52500fffc in std::vector<WasmEdge::ValType, std::allocator<WasmEdge::ValType> >::size (this=...) at /usr/include/c++/11/bits/stl_vector.h:918
918	      size() const _GLIBCXX_NOEXCEPT
#0  0x00007da52500fffc in std::vector<WasmEdge::ValType, std::allocator<WasmEdge::ValType> >::size (this=...) at /usr/include/c++/11/bits/stl_vector.h:918
#1  WasmEdge::Driver::ToolOnModule (VM=..., FuncName=..., Timeout=..., Opt=..., FuncType=...) at /work/harnesses/sources/WasmEdge/lib/driver/runtimeTool.cpp:35
#2  0x00007da5250228c4 in WasmEdge::Driver::Tool (Opt=...) at /work/harnesses/sources/WasmEdge/lib/driver/runtimeTool.cpp:511
#3  0x00007da524fe53fb in WasmEdge::Driver::UniTool (Argc=..., Argv=..., ToolSelect=...) at /work/harnesses/sources/WasmEdge/lib/driver/uniTool.cpp:69
#4  0x00007da524f454f9 in WasmEdge_Driver_UniTool (Argc=..., Argv=...) at /work/harnesses/sources/WasmEdge/lib/api/wasmedge.cpp:3384
#5  0x00005eb5a2893196 in main (Argc=..., Argv=...) at /work/harnesses/sources/WasmEdge/tools/wasmedge/wasmedge.cpp:18
rax            0x1                 1
rbx            0x504000000ed0      88235808132816
rcx            0x0                 0
rdx            0x0                 0
rsi            0x7ffd212d2d70      140725160062320
rdi            0x7ffd212d3880      140725160065152
rbp            0x7ffd212d3b00      0x7ffd212d3b00
rsp            0x7ffd212d2c70      0x7ffd212d2c70
r8             0x7ffd212d6a40      140725160077888
r9             0x0                 0
r10            0x7da525f0b2f0      138148259607280
r11            0x7da5262925d0      138148263306704
r12            0x0                 0
r13            0x7ffd212d6a40      140725160077888
r14            0x7ffd212d3ad0      140725160065744
r15            0xfffa425a5ae       17590645007790
rip            0x7da52500fffc      0x7da52500fffc <WasmEdge::Driver::ToolOnModule(WasmEdge::VM::VM&, std::string const&, std::optional<std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long, std::ratio<1, 1000000000> > > >, WasmEdge::Driver::DriverToolOptions&, WasmEdge::AST::FunctionType const&)+1573>
eflags         0x10246             [ PF ZF IF RF ]
cs             0x33                51
ss             0x2b                43
ds             0x0                 0
es             0x0                 0
fs             0x0                 0
gs             0x0                 0
k0             0x0                 0
k1             0x0                 0
k2             0x0                 0
k3             0x0                 0
k4             0x0                 0
k5             0x0                 0
k6             0x0                 0
k7             0x0                 0
A debugging session is active.

	Inferior 1 [process 2708515] will be killed.

Quit anyway? (y or n) [answered Y; input not from terminal]
warning: Error disabling address space randomization: Operation not permitted

```

### Expected State

_No response_

### Reproduction steps

[test1.wasm.txt](https://github.com/user-attachments/files/25204811/test1.wasm.txt)

### Screenshots

DESCRIPTION

### Any logs you want to share for showing the specific issue

_No response_

### Components

CLI

### WasmEdge Version or Commit you used

257467693431900d9deae79adbb2f7a6b281b4ba

### Operating system information

Ubuntu 20.04

### Hardware Architecture

amd64 (x86_64)

### Compiler flags and options

        -DWASMEDGE_BUILD_TESTS=OFF \
        -DWASMEDGE_USE_LLVM=OFF \
        -DWASMEDGE_BUILD_PLUGINS=OFF \
        -DWASMEDGE_BUILD_AOT_RUNTIME=OFF \

### PR DESCRIPTION
**Pull request by Sujanian1304**
### Summary
 Fixes a segmentation fault in ToolOnModule caused by a null pointer dereference when running in reactor mode

### Changes

-    Logic Fix: Updated the loop in lib/driver/runtimeTool.cpp to use independent if conditions. This ensures _initialize correctly sets both HasInit and FuncType.

-    Validation: Added explicit null checks for FuncType before calling ToolOnModule (Core Wasm) and ToolOnComponent (Component Model).

-    Error Handling: The tool now prints a "Function not found" error and returns EXIT_FAILURE instead of crashing if the function export is missing.

### CODE REVIEW

**Comment by hydai** [comment]
I have temporarily blocked this PR because we need to reach a consensus on how to handle this case. Please check the original issue. I will mark this PR as a draft until the discussion is finalized.

File: lib/driver/runtimeTool.cpp [hunk 1]
```diff
@@ -487,16 +487,23 @@ int Tool(struct DriverToolOptions &Opt) noexcept {
       const AST::FunctionType *FuncType = nullptr;
       for (const auto &Func : VM.getFunctionList()) {
         if (Func.first == InitFunc) {
-          // Found the init function.
```
Comment (q82419) [inline lib/driver/runtimeTool.cpp:497]: Not to remove the comment.

File: lib/driver/runtimeTool.cpp [hunk 2]
```diff
@@ -487,16 +487,23 @@ int Tool(struct DriverToolOptions &Opt) noexcept {
...
           HasInit = true;
-        } else if (Func.first == FuncName) {
-          // Found the function to invoke.
```
Comment (q82419) [inline lib/driver/runtimeTool.cpp:500]: Not to remove the comment.

File: lib/driver/runtimeTool.cpp [hunk 3]
```diff
@@ -516,12 +523,15 @@ int Tool(struct DriverToolOptions &Opt) noexcept {
       const AST::Component::FuncType *FuncType = nullptr;
       for (const auto &Func : VM.getComponentFunctionList()) {
         if (Func.first == FuncName) {
-          // Found the function to invoke.
```
Comment (q82419) [inline lib/driver/runtimeTool.cpp:526]: Not to remove the comment.

**Review by q82419 — APPROVED** [review]

**Review by q82419 — CHANGES_REQUESTED** [review]
Please fix the lint issue.

**Comment by q82419** [comment]
Please squash your commits and ensure the commitlint can pass.

**Comment by Sujanian1304** [comment]
@q82419 ,done

**Review by hydai — APPROVED** [review]
