### PR TITLE
fix(executor): synchronize HostFuncHandler callback invocation

### LINKED ISSUE #2942: Data Race in libwasmedge.so - marked by TSAN
### Summary

Data Race Detected in `libwasmedge.so`. It has been marked via using AFL++ and combination of our code generator with `TSAN` enabled.

### Current State
```
==================
WARNING: ThreadSanitizer: data race (pid=3124666)
  Write of size 1 at 0x7f97b34098b1 by thread T1:
    #0 <null> <null> (libwasmedge.so.0+0x25b065) (BuildId: ed4e8cc2e1bd47b464ead81ae0226d26d2b78ebc)
    #1 <null> <null> (libwasmedge.so.0+0x267529) (BuildId: ed4e8cc2e1bd47b464ead81ae0226d26d2b78ebc)
    #2 <null> <null> (libstdc++.so.6+0xdc25b) (BuildId: e37fe1a879783838de78cbc8c80621fa685d58a2)

  Previous write of size 1 at 0x7f97b34098b1 by main thread:
    #0 <null> <null> (libwasmedge.so.0+0x25b065) (BuildId: ed4e8cc2e1bd47b464ead81ae0226d26d2b78ebc)
    #1 <null> <null> (libwasmedge.so.0+0x15484b) (BuildId: ed4e8cc2e1bd47b464ead81ae0226d26d2b78ebc)
    #2 <null> <null> (libwasmedge.so.0+0x13fc62) (BuildId: ed4e8cc2e1bd47b464ead81ae0226d26d2b78ebc)
    #3 <null> <null> (libwasmedge.so.0+0x13fc62) (BuildId: ed4e8cc2e1bd47b464ead81ae0226d26d2b78ebc)
    #4 <null> <null> (libwasmedge.so.0+0x1258f1) (BuildId: ed4e8cc2e1bd47b464ead81ae0226d26d2b78ebc)
    #5 <null> <null> (libwasmedge.so.0+0x798c6) (BuildId: ed4e8cc2e1bd47b464ead81ae0226d26d2b78ebc)
    #6 <null> <null> (wasmedge+0xd1444) (BuildId: 0a82aaef1fd7a432928dc6417fe0a8a1f58833cd)
    #7 <null> <null> (libc.so.6+0x29d8f) (BuildId: 229b7dc509053fe4df5e29e8629911f0c3bc66dd)

  Location is global '<null>' at 0x000000000000 (SYSV00000000 (deleted)+0x98b1)

  Thread T1 (tid=3124669, running) created by main thread at:
    #0 <null> <null> (wasmedge+0x5045d) (BuildId: 0a82aaef1fd7a432928dc6417fe0a8a1f58833cd)
    #1 <null> <null> (libstdc++.so.6+0xdc328) (BuildId: e37fe1a879783838de78cbc8c80621fa685d58a2)
    #2 <null> <null> (libwasmedge.so.0+0x13fc62) (BuildId: ed4e8cc2e1bd47b464ead81ae0226d26d2b78ebc)
    #3 <null> <null> (libwasmedge.so.0+0x13fc62) (BuildId: ed4e8cc2e1bd47b464ead81ae0226d26d2b78ebc)
    #4 <null> <null> (libwasmedge.so.0+0x13fc62) (BuildId: ed4e8cc2e1bd47b464ead81ae0226d26d2b78ebc)
    #5 <null> <null> (libwasmedge.so.0+0x1258f1) (BuildId: ed4e8cc2e1bd47b464ead81ae0226d26d2b78ebc)
    #6 <null> <null> (libwasmedge.so.0+0x798c6) (BuildId: ed4e8cc2e1bd47b464ead81ae0226d26d2b78ebc)
    #7 <null> <null> (wasmedge+0xd1444) (BuildId: 0a82aaef1fd7a432928dc6417fe0a8a1f58833cd)
    #8 <null> <null> (libc.so.6+0x29d8f) (BuildId: 229b7dc509053fe4df5e29e8629911f0c3bc66dd)

SUMMARY: ThreadSanitizer: data race (/path/to/targets/WasmEdge/build/tools/wasmedge/../../lib/api/libwasmedge.so.0+0x25b065) (BuildId: ed4e8cc2e1bd47b464ead81ae0226d26d2b78ebc) 
==================
```

### Expected State

There should not be a Data Race issue.
[race.wat.txt](https://github.com/WasmEdge/WasmEdge/files/12800338/race.wat.txt) (Remove '.txt' extension when save the file)
[race.wasm.txt](https://github.com/WasmEdge/WasmEdge/files/12800373/race.wasm.txt) (Remove '.txt' extension when save the file)

### Reproduction steps

```bash
1. Build with options 'AFL_USE_TSAN=1 \
    CC=/usr/local/bin/afl-clang-fast CXX=/usr/local/bin/afl-clang-fast++ cmake .. \
    -DCMAKE_C_COMPILER_RANLIB=/usr/bin/ranlib \
    -DCMAKE_CXX_COMPILER_RANLIB=/usr/bin/ranlib \
    -DCMAKE_C_COMPILER_AR=/usr/bin/ar \
    -DCMAKE_CXX_COMPILER_AR=/usr/bin/ar \
    -DCMAKE_C_COMPILER_LAUNCHER=/usr/local/bin/afl-clang-fast \
    -DCMAKE_CXX_COMPILER_LAUNCHER=/usr/local/bin/afl-clang-fast++ \
    -DCMAKE_CXX_FLAGS="-fsanitize=thread -g" \
    -DCMAKE_C_FLAGS="-fsanitize=thread -g"'
2. Execute with flags '`wasmedge <race.wasm> _main`' (`race.wat` has been added in the `Expected State`. Simply:)
AFL command line: `afl-fuzz -i ./input -o out -t 500 -e wasm -M f0 -- /path/to/WasmEdge/build/tools/wasmedge/wasmedge @@ _main`
3. Execute with inputs '<race.wasm>'  (`race.wasm` has been added in the `Expected State`)
4. Get error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Any logs you want to share for showing the specific issue

```bash
I do understant it may be hard to reproduce a data race issue. But I have tried to contribute to the `WasmEdge` community. 

I am also adding the `race.wat`:
The code that made the `TSAN` to mark data race:

(module (memory $mem 1) (table 1 funcref)
   (elem (i32.const 0) $lift_1)
   (func
    $main
    (export "_main")
    (result i32)
    (local $i32_storage i32)
    (local $i64_storage i64)
    (local $f32_storage f32)
    (local $f64_storage f64)
    i32.const
    737
    i64.load32_s
    offset=28
    align=1
    i32.const
    0
    call_indirect
    (param i64)
    (result f32)
    i32.reinterpret_f32)
   (func
    $lift_1
    (param $param_2 i64)
    (result f32)
    (local $i32_storage i32)
    (local $i64_storage i64)
    (local $f32_storage f32)
    (local $f64_storage f64)
    i32.const
    129
    i64.load16_u
    offset=1
    align=1
    i32.const
    26
    i64.load16_s
    offset=62
    align=1
    i64.ge_s
    i32.const
    2
    i32.shr_u
    f32.reinterpret_i32
    f32.neg
    f32.trunc))
```
```


### Components

CLI

### WasmEdge Version or Commit you used

version 0.13.4-86-gdd276ee7

### Operating system information

(Ubuntu 22.04.3 LTS):

### Hardware Architecture

 Linux node1.khan22-169985.randtest.emulab.net 5.15.0-56-generic #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Compiler flags and options

 ``` CC=/usr/local/bin/afl-clang-fast CXX=/usr/local/bin/afl-clang-fast++ cmake .. \
    -DCMAKE_C_COMPILER_RANLIB=/usr/bin/ranlib \
    -DCMAKE_CXX_COMPILER_RANLIB=/usr/bin/ranlib \
    -DCMAKE_C_COMPILER_AR=/usr/bin/ar \
    -DCMAKE_CXX_COMPILER_AR=/usr/bin/ar \
    -DCMAKE_C_COMPILER_LAUNCHER=/usr/local/bin/afl-clang-fast \
    -DCMAKE_CXX_COMPILER_LAUNCHER=/usr/local/bin/afl-clang-fast++ \
    -DCMAKE_CXX_FLAGS="-fsanitize=thread -g" \
    -DCMAKE_C_FLAGS="-fsanitize=thread -g"' ```

## Additional information

A combination of AFL++ and Wasmlike, an Xsmith-based random program generator produced the snippet of code that found the issue. [Xsmith Project](https://www.flux.utah.edu/project/xsmith)

### PR DESCRIPTION
**Pull request by vishal2005025**
### Summary

Fixes a confirmed data race in the WasmEdge runtime where host function callbacks were invoked from the async execution thread without proper synchronization.

ThreadSanitizer reported a read/write race when callback registration on the main thread overlapped with callback invocation during `VM::asyncExecute()`.

### Root Cause

`HostFuncHandler` protects callback registration (`setPreHost`, `setPostHost`) using `std::unique_lock`, but the corresponding invocation paths (`invokePreHostFunc`, `invokePostHostFunc`) accessed the same state without holding a lock.

This resulted in unsynchronized reads of callback pointers and associated data across the async execution boundary.

### Changes

- Add `std::shared_lock` to:
  - `HostFuncHandler::invokePreHostFunc()`
  - `HostFuncHandler::invokePostHostFunc()`
- Preserve the existing locking model:
  - writers use `std::unique_lock`
  - readers use `std::shared_lock`

### CODE REVIEW

**Comment by vishal2005025** [comment]
@hydai @LFsWang @q82419 Please take a look and let me know if any changes are required.

File: include/executor/executor.h [hunk 1]
```diff
@@ -107,11 +107,13 @@ class HostFuncHandler {
     PostHostFunc = HostFunc;
   }
   void invokePreHostFunc() {
+    std::shared_lock Lock(Mutex);
```
Comment (hydai) [inline include/executor/executor.h]: Assuming this situation:
If a thread enters `invokePreHostFunc()` and acquires a `shared_lock(Mutex)`, then, still within the same thread, it calls `PreHostFunc(PreHostData)` while holding the `shared_lock(Mutex)`. Inside the callback, it attempts to call `setPreHost()`, which tries to acquire a `unique_lock(Mutex)`.

The `unique_lock(Mutex)` blocks forever, waiting for the `shared_lock(Mutex)` to be released. However, the `shared_lock(Mutex)` won't be released until the callback returns, but the callback is blocked. This situation could lead to a deadlock.

To fix it, I prefer the following patch instead:

```patch
diff --git a/include/executor/executor.h b/include/executor/executor.h
index 089cc661..5c363db7 100644
--- a/include/executor/executor.h
+++ b/include/executor/executor.h
@@ -107,15 +107,27 @@ public:
     PostHostFunc = HostFunc;
   }
   void invokePreHostFunc() {
-    std::shared_lock Lock(Mutex);
-    if (PreHostFunc.operator bool()) {
-      PreHostFunc(PreHostData);
+    std::function<void(void *)> HostFunc;
+    void *HostData = nullptr;
+    {
+      std::shared_lock Lock(Mutex);
+      HostFunc = PreHostFunc;
+      HostData = PreHostData;
+    }
+    if (HostFunc.operator bool()) {
+      HostFunc(HostData);
     }
   }
   void invokePostHostFunc() {
-    std::shared_lock Lock(Mutex);
-    if (PostHostFunc.operator bool()) {
-      PostHostFunc(PostHostData);
+    std::function<void(void *)> HostFunc;
+    void *HostData = nullptr;
+    {
+      std::shared_lock Lock(Mutex);
+      HostFunc = PostHostFunc;
+      HostData = PostHostData;
+    }
+    if (HostFunc.operator bool()) {
+      HostFunc(HostData);
     }
   }
```

**Comment by vishal2005025** [comment]
@hydai Thanks for pointing out the reentrancy concern.
I’ve updated the patch to snapshot the callback and data under a shared lock and invoke the callback after releasing the lock, as suggested. This avoids both the TSAN-reported race and the potential deadlock.
Please let me know if any further changes are needed. Thanks!
