### PR TITLE
fix(component,loader): functype grammar and i64 resource rep

### LINKED ISSUE #4702: feat: Component Model: Loader completion and pass spec tests
### Summary

Currently, some component model tests for loader failed.
We should pass the tests for ensure completion of component model loader.

### Details

Depends on PR #4695 

- [ ] component-model/func.wast
- [ ] component-model/wrong-order.wast

### Appendix

_No response_

### PR DESCRIPTION
**Pull request by q82419**
## Checklist

Before submitting this PR, please ensure the following:

- [x] **DCO Signed-off**: All commits are signed-off (`git commit -s`). CI workflows will only be approved if DCO check is passed.
- [x] **Commit Messages**: Run `commitlint` on your commit messages to ensure they meet the [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) standards.
- [x] **Local Tests Passed**: Provide a screenshot or logs below to prove that you have passed the test suites locally.

## Test Evidence

---

> **Important:** This PR will be automatically closed if the above requirements are not met.

> **Tip:** If you want to run CI jobs on GitHub, you can create a PR to your own forked repository to trigger the workflows.

### CODE REVIEW

**Comment by q82419** [comment]
replace #4709

**Comment by q82419** [comment]
close #4702 
It's the last test case

File: include/ast/component/type.h [hunk 1]
```diff
@@ -436,9 +445,15 @@ class ResourceType {
   std::optional<uint32_t> &getDestructor() noexcept { return Dtor; }
   std::optional<uint32_t> &getCallback() noexcept { return DtorCallback; }
 
+  bool isI64Rep() const noexcept { return IsI64Rep; }
```
Comment (dannypsnl) [inline include/ast/component/type.h]: What's `Rep`? Maybe we should have full name for function?

Comment (q82419) [reply include/ast/component/type.h]: Fixed

File: test/spec/spectest.cpp [hunk 2]
```diff
@@ -342,7 +342,6 @@ std::map<std::string, ComponentModelSupport> ComponentModelFolders = {
     {"types",                   {true, false, false, false}},
     {"very-nested",             {true, false, false, false}},
     {"virtualize",              {true, false, false, false}},
-    {"wrong-order",             {false, false, false, false}},
```
Comment (hydai) [inline test/spec/spectest.cpp:345]: What's the reason to remove it?

**Review by hydai — CHANGES_REQUESTED** [review]

File: test/spec/spectest.cpp (hunk 2 above)
Comment (q82419) [reply test/spec/spectest.cpp:345]: The test case is only pure WASM tests, not component-model, but selected in wasm-tools.
I'll remove this folder in the next tag of wasmedge-spectest.

Comment (hydai) [reply test/spec/spectest.cpp:345]: Got it

**Review by hydai — APPROVED** [review]

**Review by dannypsnl — APPROVED** [review]
